"""Add due_date field to Todo model

Revision ID: 74933dc4b6f8
Revises: 
Create Date: 2025-10-30 19:49:20.947403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74933dc4b6f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###
